### ISSUE TITLE
Room and user highlights

### ISSUE THREAD

**Issue by rubdos** [zwieberl/matrix_bot_api#6]
If I type `@room` or `@myfriend:myserver.ext`, Element/Riot renders it as a mention in red/in a bubble:

![room-highlight](https://user-images.githubusercontent.com/1263440/89130561-2249bf80-d506-11ea-9568-e50daf163f54.png)

When my bot writes a message that contains `@room`, it does not have any highlight:

![cyber-mention](https://user-images.githubusercontent.com/1263440/89130560-2249bf80-d506-11ea-818e-9a980da44eaa.png)

It is not a problem with `@myfriend:myserver.ext`, because that *does* seem to trigger a highlight, although without the nice bubble rendered around it.

I seem to notice it has to do with "tweaks" that are set on messages (`set_tweak: "highlight"` is something I can find in the Javascript `matrix-js-sdk`), but I cannot seem to wrap my head around it. Moreover, I don't think this is exposed in the API?

Do you happen to know how to get mentions to work? If you can point me in the right direction, I can drop you a pull request. Thanks!

**Comment by zwieberl** [comment]
Hm, this is interesting, as I can't reproduce that. 
I'm using my stateless-example with the echo-command to test this. 
When I tell the bot to echo a message that contains `@room`, its echo-response gets highlighted (like in your first picture). When I modify the code, such that each echo will be prefixed with a `@room` it gets highlighted every time, as well.
Could you test this as well, please? I _think_ the mention-mechanism is completely client-side parsing, but I don't know for sure.

**Comment by rubdos** [comment]
Hmm, I am sending an HTML version along; maybe it's that?

```rust
use matrix_bot_api::*;

pub trait ActiveBotExt {
    fn send_markdown_message(&self, msg: &str, room: &str, msgtype: MessageType);
}

impl ActiveBotExt for ActiveBot {
    fn send_markdown_message(&self, msg: &str, room: &str, msgtype: MessageType) {
        let html = comrak::markdown_to_html(msg, &comrak::ComrakOptions::default());
        self.send_html_message(msg, &html, room, msgtype);
    }
}
```

I'm using that as extension trait, to send Markdown messages.

I've added an echo call to my bot, that doesn't use markdown/html, albeit in my `MessageHandler` instead of `StatelessHandler::register_handle`:

```rust
        if let Some("hi") = matrix_bot_api::handlers::extract_command(body, "!") {
            active.send_message(
                &format!("Hello, {}, {}", msg.sender, msg.body),
                &msg.room,
                MessageType::TextMessage,
            );
        }
```

With this as result:

![2020-08-04--09-37-04-edit](https://user-images.githubusercontent.com/1263440/89266427-35f44380-d636-11ea-8a38-636947767443.png)

I would have again expected `@room` in a balloon.

View Source gives me:

```json
{
  "type": "m.room.message",
  "sender": "@twbot:rubdos.be",
  "content": {
    "body": "Hello, @rubdos:rubdos.be, !hi @room",
    "msgtype": "m.text"
  },
  "origin_server_ts": 1596526446237,
  "unsigned": {
    "age": 329
  },
  "event_id": "$XPGlSpMoswWZi21phMxArV4grvaCExrIA8lM8PyEuoM",
  "room_id": "!eQgyOrETvIhrmQAnpm:rubdos.be"
}
```

Feel free to join that room for experiments (ping @rubdos:rubdos.be for invite), I can give you the source as well if you want.

**Comment by zwieberl** [comment]
This is really weird. 

> I've added an echo call to my bot, that doesn't use markdown/html, albeit in my MessageHandler instead of StatelessHandler::register_handle

This should not matter, its the same send-function. Its just how the handler-function gets called.

> I would have again expected @room in a balloon.

Yes, I would, too. I replicated HTML-sending thus:
```
    handler.register_handle("echo", |bot, message, tail| {
        let raw = format!("# @room: {}", tail);
        let html = format!("<h1>@room: {}</h1>\n", tail);
        bot.send_html_message(&raw, &html,
            &message.room,
            MessageType::TextMessage,
        );
        HandleResult::StopHandling
    });
```
and got a balloon (a big balloon too :-) ):
![html-echo](https://user-images.githubusercontent.com/2752876/89419857-396cf500-d732-11ea-9adb-cfcf58e7c9a1.png)
```
  "content": {
    "msgtype": "m.text",
    "body": "# @room:  Testing",
    "formatted_body": "<h1>@room:  Testing</h1>\n",
    "format": "org.matrix.custom.html"
  },
  "type": "m.room.message"
```

Then I tried to copy your plain echo function:
```
    handler.register_handle("echo", |bot, message, tail| {
         bot.send_message(
             &format!("Hello {} {}", message.sender, tail),
             &message.room,
             MessageType::TextMessage,
         );
        HandleResult::StopHandling
    });
```
this gives me:
![plain-echo](https://user-images.githubusercontent.com/2752876/89419997-68836680-d732-11ea-90a6-cd6dd9ebd3fe.png)
```
  "content": {
    "msgtype": "m.text",
    "body": "Hello @<snip> hello @room "
  },
  "type": "m.room.message",
```

So it works for me no matter what I do, and the sources (rust-code as well as message-sources) seem to be identical.

Are you using a different version of Element maybe? I'm using Element version: 1.7.1

**Comment by rubdos** [comment]
```
❯ pacman -Qi element-desktop                1221ms  Sat 08 Aug 2020 03:44:20 PM UTC
Name            : element-desktop
Version         : 1.7.1-1
```

This is getting really weird then. I'm using `matrix_bot_api` on crates.io, I'll try using from git.

EDIT: nope, git version doesn't fix it either.

**Comment by zwieberl** [comment]
:-/ Damn. 
Ok, we probably should ask around upstream what triggers the creation of the balloons then.

**Comment by rubdos** [comment]
I suppose. I do not know what channels should be used for that; what would you suggest?

I also noticed that in a channel I link through Discord (via the [Discord Bridge](https://github.com/Half-Shot/matrix-appservice-discord/)), the conversion for mentions happens and they correctly write `@rubdos:rubdos.be`, but no balloon either.

It's weird. Maybe I have an outdated Synapse?

**Comment by zwieberl** [comment]
I've asked around a bit and somebody raised a good point: Does your bot have permissions to notify all in your room? 
Room-settings -> Roles & Permissions

**Comment by rubdos** [comment]
Oh my god. Now I feel dumb.

![2020-08-11--11-48-47](https://user-images.githubusercontent.com/1263440/89883682-c39cd980-dbc8-11ea-90c1-6fee468b70d4.png)

So sorry for bothering you with this. I set @room to Default and it's solved. Thanks for helping me out!

Can I return the favour by making a `feature = "markdown"` for you? :-)

**Comment by zwieberl** [comment]
Haha, don't worry, I didn't think of it either. Glad its solved! 

PRs are of course always welcome :-)
But I probably have to switch the backend soon, as Fractal is dropping their own Matrix-API crate and is going to use matrix-rust-sdk in the future. It would probably be better to wait for that (although I have no idea when I will find time for it :-D )
